-- ============================================================================
-- ORACLE EMPLOYEE MANAGEMENT SYSTEM - CORRECTED CREATE TABLE STATEMENTS
-- IMPORTANT: Run in this exact order to avoid errors
-- ============================================================================

-- ============================================================================
-- STEP 1: CREATE COUNTRIES TABLE (Create First - No Dependencies)
-- ============================================================================
CREATE TABLE Countries (
    Country_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Country_Name VARCHAR2(100) NOT NULL UNIQUE,
    Country_Code VARCHAR2(10) NOT NULL UNIQUE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_country_code_length CHECK (LENGTH(Country_Code) = 2)
);

COMMIT;
PROMPT "Countries table created successfully!";

-- ============================================================================
-- STEP 2: CREATE DEPARTMENTS TABLE (Depends on Countries)
-- ============================================================================
CREATE TABLE Departments (
    Department_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Department_Name VARCHAR2(100) NOT NULL,
    Location VARCHAR2(100),
    Country_ID NUMBER NOT NULL,
    Budget NUMBER(12,2) DEFAULT 0,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dept_country FOREIGN KEY (Country_ID) 
        REFERENCES Countries(Country_ID) ON DELETE CASCADE,
    CONSTRAINT chk_budget_positive CHECK (Budget >= 0),
    CONSTRAINT uk_dept_name_country UNIQUE (Department_Name, Country_ID)
);

COMMIT;
PROMPT "Departments table created successfully!";

-- ============================================================================
-- STEP 3: CREATE ROLES TABLE (Create Now - No Dependencies)
-- ============================================================================
CREATE TABLE Roles (
    Role_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Role_Name VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(500),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
PROMPT "Roles table created successfully!";

-- ============================================================================
-- STEP 4: CREATE EMPLOYEES TABLE (Depends on Departments and Roles)
-- CORRECTED: Changed ON DELETE SET NULL to CASCADE for all foreign keys
-- ============================================================================
CREATE TABLE Employees (
    Employee_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone_Number VARCHAR2(15),
    Address VARCHAR2(255),
    Hire_Date DATE DEFAULT SYSDATE NOT NULL,
    Department_ID NUMBER NOT NULL,
    Role_ID NUMBER NOT NULL,
    Salary NUMBER(10,2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Active',
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emp_dept FOREIGN KEY (Department_ID) 
        REFERENCES Departments(Department_ID) ON DELETE CASCADE,
    CONSTRAINT fk_emp_role FOREIGN KEY (Role_ID) 
        REFERENCES Roles(Role_ID) ON DELETE CASCADE,
    CONSTRAINT chk_salary_positive CHECK (Salary > 0),
    CONSTRAINT chk_email_format CHECK (Email LIKE '%@%.%'),
    CONSTRAINT chk_emp_status CHECK (Status IN ('Active', 'Inactive', 'On Leave'))
);

COMMIT;
PROMPT "Employees table created successfully!";

-- ============================================================================
-- STEP 5: CREATE MANAGERS TABLE (Depends on Employees and Departments)
-- ============================================================================
CREATE TABLE Managers (
    Manager_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Employee_ID NUMBER UNIQUE NOT NULL,
    Department_ID NUMBER NOT NULL,
    Manager_Since DATE DEFAULT SYSDATE,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mgr_emp FOREIGN KEY (Employee_ID) 
        REFERENCES Employees(Employee_ID) ON DELETE CASCADE,
    CONSTRAINT fk_mgr_dept FOREIGN KEY (Department_ID) 
        REFERENCES Departments(Department_ID) ON DELETE CASCADE
);

COMMIT;
PROMPT "Managers table created successfully!";

-- ============================================================================
-- STEP 6: CREATE ALLOWANCES TABLE (Depends on Roles)
-- CORRECTED: Removed SYSDATE from CHECK constraint
-- ============================================================================
CREATE TABLE Allowances (
    Allowance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Role_ID NUMBER NOT NULL,
    Allowance_Name VARCHAR2(100) NOT NULL,
    Allowance_Amount NUMBER(10,2) NOT NULL,
    Effective_Date DATE DEFAULT SYSDATE,
    Expiry_Date DATE,
    Is_Applicable CHAR(1) DEFAULT 'Y',
    Comments VARCHAR2(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_allow_role FOREIGN KEY (Role_ID) 
        REFERENCES Roles(Role_ID) ON DELETE CASCADE,
    CONSTRAINT chk_allow_amount CHECK (Allowance_Amount > 0),
    CONSTRAINT chk_is_applicable CHECK (Is_Applicable IN ('Y', 'N'))
);

COMMIT;
PROMPT "Allowances table created successfully!";

-- ============================================================================
-- STEP 7: CREATE ATTENDANCE TABLE (Depends on Employees)
-- ============================================================================
CREATE TABLE Attendance (
    Attendance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Employee_ID NUMBER NOT NULL,
    Attendance_Date DATE NOT NULL,
    Check_In_Time TIMESTAMP,
    Check_Out_Time TIMESTAMP,
    Status VARCHAR2(20) DEFAULT 'Present',
    Notes VARCHAR2(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_att_emp FOREIGN KEY (Employee_ID) 
        REFERENCES Employees(Employee_ID) ON DELETE CASCADE,
    CONSTRAINT chk_att_status CHECK (Status IN ('Present', 'Absent', 'Leave', 'Late')),
    CONSTRAINT chk_check_times CHECK (Check_In_Time <= Check_Out_Time OR Check_Out_Time IS NULL),
    CONSTRAINT uk_attendance UNIQUE (Employee_ID, Attendance_Date)
);

COMMIT;
PROMPT "Attendance table created successfully!";

-- ============================================================================
-- STEP 8: CREATE PERFORMANCE EVALUATION TABLE (Depends on Employees)
-- ============================================================================
CREATE TABLE Performance_Evaluations (
    Evaluation_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Employee_ID NUMBER NOT NULL,
    Evaluator_ID NUMBER,
    Evaluation_Date DATE DEFAULT SYSDATE,
    Performance_Score NUMBER(3,2),
    Comments VARCHAR2(500),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_perf_emp FOREIGN KEY (Employee_ID) 
        REFERENCES Employees(Employee_ID) ON DELETE CASCADE,
    CONSTRAINT fk_perf_evaluator FOREIGN KEY (Evaluator_ID) 
        REFERENCES Employees(Employee_ID) ON DELETE SET NULL,
    CONSTRAINT chk_perf_score CHECK (Performance_Score BETWEEN 0 AND 5)
);

COMMIT;
PROMPT "Performance_Evaluations table created successfully!";

-- ============================================================================
-- STEP 9: CREATE SALARY HISTORY TABLE (Depends on Employees)
-- ============================================================================
CREATE TABLE Salary_History (
    Salary_History_ID NUMBER GENERATED BY DEFAULT AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 
        PRIMARY KEY,
    Employee_ID NUMBER NOT NULL,
    Previous_Salary NUMBER(10,2),
    New_Salary NUMBER(10,2) NOT NULL,
    Change_Date DATE DEFAULT SYSDATE,
    Reason VARCHAR2(255),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sal_emp FOREIGN KEY (Employee_ID) 
        REFERENCES Employees(Employee_ID) ON DELETE CASCADE,
    CONSTRAINT chk_new_salary CHECK (New_Salary > 0)
);

COMMIT;
PROMPT "Salary_History table created successfully!";

-- ============================================================================
-- VERIFICATION QUERY - Run this to verify all tables are created
-- ============================================================================
PROMPT "=== VERIFYING ALL TABLES ===";
SELECT table_name FROM user_tables 
WHERE table_name IN ('COUNTRIES', 'DEPARTMENTS', 'ROLES', 'EMPLOYEES', 
                     'MANAGERS', 'ALLOWANCES', 'ATTENDANCE', 
                     'PERFORMANCE_EVALUATIONS', 'SALARY_HISTORY')
ORDER BY table_name;

PROMPT "=== ALL TABLES CREATED SUCCESSFULLY! ===";